# generated by datamodel-codegen:
#   filename:  jsonschema.json
#   timestamp: 2024-01-03T06:59:17+00:00

from __future__ import annotations

from typing import List, Union

from pydantic import BaseModel


class ModelItem(BaseModel):
    id: Union[int, str]
    name: str
    professor: str
    credits: int
    registration_code: str


class Model(BaseModel):
    __root__: List[ModelItem]
